- hosts: vns
  tasks:

    - name: Run ls to test connection and ability
      shell: sudo cat /var/named/chroot/etc/named.forwards 
      register: named_forwards

    - debug: msg="{{ named_forwards.stdout }}"

    - debug: msg="{{ named_forwards.stderr }}"

 #     - name: Register a variable
 #       ansible.builtin.shell: cat /var/named/chroot/etc/named.forwards
 #       register: named.forwards_contents

 #     - name: Register a variable
 #       ansible.builtin.shell: cat vns/named.forwards
 #       register: vns_named_forwards_contents

  
  - template:
      src: vns/named.forwards
      dest: /var/named/chroot/etc/named.forwards
      owner: root
      group: named
      mode: 0664
  #  when: named.forwards_contents.stdout != vns.named.forwards_contents.stdout

  #handlers:
  #  - name: restart named.service
  #    service: name=named.service state=restarted

