- hosts: vns
  tasks:

    - name: Run ls to test connection and ability
      shell: sudo cat /var/named/chroot/etc/named.forwards 
      register: named_forwards

#    - debug: msg="{{ named_forwards.stdout }}"

#    - debug: msg="{{ named_forwards.stderr }}"
  
    - template:
        src: vns/named.forwards
        dest: /var/named/chroot/etc/named.forwards
        owner: root
        group: named
        mode: 0664
      when: named_forwards.changed

  handlers:
    - name: restart named.service
      service: name=named.service state=restarted

